package com.epam.huntingService.service;

public class ServiceConstants {
    public static final String LOGIN_SERVICE = "/Login";
    public static final String LOGOUT_SERVICE = "/LogOutService";
    public static final String SHOW_ORGANIZATION_SERVICE = "/ShowOrganization";
    public static final String SHOW_HUNTING_GROUND_SERVICE = "/ShowHuntingGround";
    public static final String SHOW_HUNTING_GROUND_BY_ANIMAL_SERVICE = "/ShowHuntingGroundsByAnimal";
    public static final String FORWARD_SERVICE = "/Forward";
    public static final String REGISTER_USER_SERVICE = "/RegisterUser";
    public static final String DELETE_USER_SERVICE = "/DeleteUser";
    public static final String EDIT_PROFILE_SERVICE = "/EditProfile";
    public static final String CHANGE_PASSWORD_SERVICE = "/ChangePassword";
    public static final String ADD_TO_CART_SERVICE = "/AddToCart";
    public static final String REMOVE_FROM_CART_SERVICE = "/RemoveFromCart";
    public static final String ORDER_DAILY_PERMIT_SERVICE = "/OrderDailyPermit";
    public static final String ORDER_SEASON_PERMIT_SERVICE = "/OrderSeasonPermit";
    public static final String UPLOAD_DOCUMENT_SERVICE = "/UploadHunterDocument";
    public static final String DOWNLOAD_HUNTER_DOCUMENT_SERVICE = "/DownloadHunterDocument";
    public static final String SEARCH_SERVICE = "/Search";
    public static final String PREPARE_LIMIT_INFO_SERVICE = "/PrepareLimitInfo";
    public static final String SHOW_ORDERED_PERMITS_SERVICE = "/ShowOrderedPermits";
    public static final String CHANGE_ROLE_SERVICE = "/ChangeRole";
    public static final String SHOW_ALL_USERS_BY_CATEGORIES_SERVICE = "/ShowAllUsersByCategories";
    public static final String SHOW_ALL_HUNTING_GROUNDS_SERVICE = "/ShowAllHuntingGrounds";
    public static final String ADD_HUNTING_GROUND_SERVICE = "/AddHuntingGround";
    public static final String PREPARE_HUNTING_GROUND_EDITING_SERVICE = "/PrepareHuntingGroundEditing";
    public static final String EDIT_HUNTING_GROUND_SERVICE = "/EditHuntingGround";
    public static final String SHOW_ALL_ORGANIZATIONS_SERVICE = "/ShowAllOrganizations";
    public static final String ADD_ORGANIZATION_SERVICE = "/AddOrganization";
    public static final String PREPARE_ORGANIZATION_EDITING_SERVICE = "/PrepareOrganizationEditing";
    public static final String EDIT_ORGANIZATION_SERVICE = "/EditOrganization";
    public static final String SHOW_ALL_ANIMALS_SERVICE = "/ShowAllAnimals";
    public static final String ADD_ANIMAL_SERVICE = "/AddAnimal";
    public static final String PREPARE_ANIMAL_EDITING_SERVICE = "/PrepareAnimalEditing";
    public static final String EDIT_ANIMAL_SERVICE = "/EditAnimal";
    public static final String SHOW_ALL_PERMITS_SERVICE = "/ShowAllPermits";
    public static final String SHOW_ANIMALS_LIMIT_SERVICE = "/ShowAnimalsLimit";
    public static final String ADD_ANIMAL_LIMIT_SERVICE = "/AddAnimalLimit";
    public static final String PREPARE_ANIMAL_LIMIT_EDITING_SERVICE = "/PrepareAnimalLimitEditing";
    public static final String EDIT_ANIMAL_LIMIT_SERVICE = "/EditAnimalLimit";
    public static final String SHOW_QUOTA_SERVICE = "/ShowQuota";
    public static final String ADD_QUOTA_SERVICE = "/AddQuota";
    public static final String PREPARE_QUOTA_EDITING_SERVICE = "/PrepareQuotaEditing";
    public static final String EDIT_QUOTA_SERVICE = "/EditQuota";
    public static final String CHANGE_LANGUAGE_SERVICE = "/ChangeLanguage";
    public static final String ERROR_SERVICE = "error";
}
