package com.epam.huntingService.util;

public class ErrorConstants {
    public static final String AUTH_ERROR = "errorLogin";
    public static final String LOGIN_ERROR = "error.login";
    public static final String WRONG_YEAR_DATA = "wrongYear";
    public static final String YEAR_ERROR = "error.year";
    public static final String WRONG_ANIMAL_DATA = "animalIsExist";
    public static final String ANIMAL_ERROR = "error.animal.exist";
    public static final String EMPTY_DATA = "emptyFields";
    public static final String FILL_DATA_ERROR = "error.empty.fields";
    public static final String WRONG_FILE_DATA = "incorrectFile";
    public static final String FILE_ERROR = "error.file";
    public static final String WRONG_HUNTING_DATE = "wrongHuntingDate";
    public static final String HUNTING_DATE_ERROR = "error.hunting.date";
    public static final String WRONG_ORDERED_ANIMALS_COUNT = "wrongOrderedAnimalsCount";
    public static final String ORDERED_ANIMALS_COUNT_ERROR = "error.ordered.animals";
    public static final String WRONG_EMAIL = "notCorrectEmail";
    public static final String EMAIL_ERROR = "error.email";
    public static final String WRONG_PHONE = "notCorrectPhone";
    public static final String PHONE_ERROR = "error.phone";
    public static final String WRONG_PASSWORD = "notCorrectPassword";
    public static final String PASSWORD_ERROR = "error.password";
    public static final String WRONG_EQUALITY_ERROR = "oldPasswordIsIncorrect";
    public static final String PASSWORD_EQUALITY_ERROR = "error.password.equality";
    public static final String WRONG_ORGANIZATIONS_EQUALITY = "notEqualOrganizations";
    public static final String ORGANIZATIONS_EQUALITY_ERROR = "error.org.equality";
    public static final String WRONG_HUNTING_GROUND_NAME = "huntingGroundExistAlready";
    public static final String HUNTING_GROUND_NAME_ERROR = "error.hunting.ground.name";
    public static final String ANIMAL_IS_NOT_EXIST_IN_SERVICE = "animalIsNotExist";
    public static final String NOT_EXISTING_ANIMAL_ERROR = "error.animal.not.exist";
    public static final String WRONG_LIMIT_DATA = "animalLimitIsExist";
    public static final String LIMIT_DATA_ERROR = "error.limit.set.already";
    public static final String ORGANIZATION_EXISTS_ALREADY = "organizationExistAlready";
    public static final String ORGANIZATION_EXISTS_ERROR = "error.org.exists.already";
    public static final String WRONG_LOGIN = "loginIsExist";
    public static final String LOGIN_EXISTS_ERROR = "Login already exists";
    public static final String EMPTY_SEARCH = "emptySearch";
    public static final String EMPTY_SEARCH_ERROR = "error.search";
    public static final String FOUND_NOTHING = "foundNothing";
    public static final String FOUND_NOTHING_ERROR = "error.found.nothing";
    public static final String UPLOAD_COMPLETE = "uploadComplete";
    public static final String UPLOAD_SUCCESS_MESSAGE = "alert.upload";
    public static final String UPDATE_PROFILE_COMPLETE = "successfullyUpdatedUser";
    public static final String UPDATE_PROFILE_SUCCESS_MESSAGE = "alert.update.profile";
}
